# Generated by Django 3.2 on 2023-02-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230223_0624'),
        ('reviews', '0003_auto_20230223_1101'),
    ]

    operations = [
    ]
